version: '3'

services:
  postgres_database:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080